from .alteracao_senha_routes import *
from .auth_routes import *
from .centro_routes import *
from .estorno_routes import *
from .filial_routes import *
from .mudar_status_routes import *
from .recebimento_routes import *
from .responsavel_routes import *
from .menu_routes import *
from .tables_routes import *